{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.cloud",
    "module": "gapic-google-cloud-maps-automotivemaps-v1-java",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.api",
          "module": "gax",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "com.google.api",
          "module": "gax-grpc",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "com.google.api",
          "module": "gax-httpjson",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.55.1"
          }
        },
        {
          "group": "com.google.api.grpc",
          "module": "proto-google-cloud-maps-automotivemaps-v1-java",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gapic-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "url": "gapic-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "size": 36590,
          "sha512": "30475b692fdf646fa58846229dbfdd11aea2f0648f65835fdfc658eade2d0f9b99ef100a4d3a7e5f34e0320e4cc17a6215f98ae691910e78d78d433b81be4c79",
          "sha256": "303ea9a60cdf63262fd958af43e88d2456500c1dcb743b89fe67709cfd053aa9",
          "sha1": "21ba00f24cdae27d83a50a4823d019f7d1b2a73f",
          "md5": "2c2a9afaf8e67fbe12ff287df99d396a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.api",
          "module": "gax",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "com.google.api",
          "module": "gax-grpc",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "com.google.api",
          "module": "gax-httpjson",
          "version": {
            "requires": "2.30.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.55.1"
          }
        },
        {
          "group": "com.google.api.grpc",
          "module": "proto-google-cloud-maps-automotivemaps-v1-java",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "gapic-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "url": "gapic-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "size": 36590,
          "sha512": "30475b692fdf646fa58846229dbfdd11aea2f0648f65835fdfc658eade2d0f9b99ef100a4d3a7e5f34e0320e4cc17a6215f98ae691910e78d78d433b81be4c79",
          "sha256": "303ea9a60cdf63262fd958af43e88d2456500c1dcb743b89fe67709cfd053aa9",
          "sha1": "21ba00f24cdae27d83a50a4823d019f7d1b2a73f",
          "md5": "2c2a9afaf8e67fbe12ff287df99d396a"
        }
      ]
    }
  ]
}
