{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.api.grpc",
    "module": "grpc-google-cloud-maps-automotivemaps-v1-java",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.api.grpc",
          "module": "proto-google-cloud-maps-automotivemaps-v1-java",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "grpc-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "url": "grpc-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "size": 13480,
          "sha512": "430973b7f5764fd9b66086d642ac21e52a2fc528f8af3917ed714b77080b8172457a920a15bb3b287285dfe6874f4f2dc951f096ddd044912aeda2084703d01b",
          "sha256": "e419289c62ed871df8fee70b0664ce1d51fbeef73ae9e6d400da702d9f6e846d",
          "sha1": "aca0e85b4e0e3f93166709a29e746fac139d12e7",
          "md5": "b9a7f31a08061c3473e23a6f78007373"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.53.0"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.53.0"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.api.grpc",
          "module": "proto-google-cloud-maps-automotivemaps-v1-java",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "grpc-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "url": "grpc-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "size": 13480,
          "sha512": "430973b7f5764fd9b66086d642ac21e52a2fc528f8af3917ed714b77080b8172457a920a15bb3b287285dfe6874f4f2dc951f096ddd044912aeda2084703d01b",
          "sha256": "e419289c62ed871df8fee70b0664ce1d51fbeef73ae9e6d400da702d9f6e846d",
          "sha1": "aca0e85b4e0e3f93166709a29e746fac139d12e7",
          "md5": "b9a7f31a08061c3473e23a6f78007373"
        }
      ]
    }
  ]
}
