{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.api.grpc",
    "module": "proto-google-cloud-maps-automotivemaps-v1-java",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "proto-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "url": "proto-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "size": 1180787,
          "sha512": "19ab46ef949026a9839dd0142622c9f2497e8f81fca41d510785f702ea6b44ac26cf770f0595ebdfa962a2e6bdccf0af005edaface6e682f22684b7cd408dd40",
          "sha256": "d675e0a2d696c066ff65a35c5599bb3eebbd56fa244747d0745444a1d224153b",
          "sha1": "b552933342c4f89f942cb82c91b933dfb895c909",
          "md5": "1633a8c8f2a45e77750aa76d26267305"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.protobuf",
          "module": "protobuf-java",
          "version": {
            "requires": "3.23.2"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "32.0.1-jre"
          }
        },
        {
          "group": "com.google.api",
          "module": "api-common",
          "version": {
            "requires": "2.7.0"
          }
        },
        {
          "group": "com.google.api.grpc",
          "module": "proto-google-common-protos",
          "version": {
            "requires": "2.15.0"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "proto-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "url": "proto-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "size": 1180787,
          "sha512": "19ab46ef949026a9839dd0142622c9f2497e8f81fca41d510785f702ea6b44ac26cf770f0595ebdfa962a2e6bdccf0af005edaface6e682f22684b7cd408dd40",
          "sha256": "d675e0a2d696c066ff65a35c5599bb3eebbd56fa244747d0745444a1d224153b",
          "sha1": "b552933342c4f89f942cb82c91b933dfb895c909",
          "md5": "1633a8c8f2a45e77750aa76d26267305"
        }
      ]
    }
  ]
}
