{
  "formatVersion": "1.1",
  "component": {
    "group": "com.google.api.grpc",
    "module": "grpc-google-cloud-maps-automotivemaps-v1-java",
    "version": "0.0.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.api.grpc",
          "module": "proto-google-cloud-maps-automotivemaps-v1-java",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "grpc-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "url": "grpc-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "size": 14023,
          "sha512": "aa2cb6296c4915095f88fc9abc0324169934edf45e0fb2e7b63f33432e8eacdb3a43f235b239a115e3f7f4250a99cb95c49daa1d521792016e2412bfee0e4149",
          "sha256": "315a1b37815bddd987ac93e6ec7a82b92deaf446367e13af950d4a9d3761b965",
          "sha1": "6d4f86486ceeddf7aca927b76725c0128ad3ef5b",
          "md5": "89875646e062a68001e589104df1f89b"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.grpc",
          "module": "grpc-stub",
          "version": {
            "requires": "1.55.1"
          }
        },
        {
          "group": "io.grpc",
          "module": "grpc-protobuf",
          "version": {
            "requires": "1.55.1"
          }
        },
        {
          "group": "javax.annotation",
          "module": "javax.annotation-api",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.google.api.grpc",
          "module": "proto-google-cloud-maps-automotivemaps-v1-java",
          "version": {
            "requires": "0.0.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "grpc-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "url": "grpc-google-cloud-maps-automotivemaps-v1-java-0.0.0-SNAPSHOT.jar",
          "size": 14023,
          "sha512": "aa2cb6296c4915095f88fc9abc0324169934edf45e0fb2e7b63f33432e8eacdb3a43f235b239a115e3f7f4250a99cb95c49daa1d521792016e2412bfee0e4149",
          "sha256": "315a1b37815bddd987ac93e6ec7a82b92deaf446367e13af950d4a9d3761b965",
          "sha1": "6d4f86486ceeddf7aca927b76725c0128ad3ef5b",
          "md5": "89875646e062a68001e589104df1f89b"
        }
      ]
    }
  ]
}
